apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 823915348487.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 823915348487.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 5557ec29
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
